# Generated by Django 4.2.7 on 2023-11-21 17:32

from django.db import migrations, models
import server.folder_handler
import server.validators.image_validators


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='icon',
        ),
        migrations.AddField(
            model_name='server',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.folder_handler.prepare_server_banner_path, validators=[server.validators.image_validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='server',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.folder_handler.prepare_server_icon_path, validators=[server.validators.image_validators.validate_icon_size, server.validators.image_validators.validate_image_file_extension]),
        ),
    ]
