# Generated by Django 4.2.7 on 2023-11-18 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_server_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_server', to='server.server'),
        ),
    ]
