# Generated by Django 4.2.7 on 2023-11-20 08:23

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_channel_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=server.models.get_category_icon_path),
        ),
    ]
